### ISSUE TITLE
Failed to install solc 0.8.18 

### ISSUE THREAD

**Issue by alexbakers** [foundry-rs/foundry-toolchain#27]
Default test:

```
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
```

Error:

```
installing solc version "0.8.18"
Failed to install solc 0.8.18: Checksum mismatch for version 0.8.18
Error: 
Checksum mismatch for version 0.8.18
Error: Process completed with exit code 1.
```
