### ISSUE TITLE
specifying versions

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry-toolchain#35]
Is it possible to specify a version like so : nightly-d369d2486f85576eec4ca41d277391dfdae21ba7

Are nightly and 0.1.0 and 0.2.0 the only possible values?

**Comment by relyt29** [comment]
same issue, need to be able to pin to a specific foundry commit because foundry has a bug and our CI is failing

until foundry team fixes their bug we need to be able to pin to a specific known-good version of foundry

**Comment by relyt29** [comment]
it appears version specification might work, e.g. like so:

```
name: FoundryTest

on: [pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly-ca67d15f4abd46394b324c50e21e66f306a1162d"

```
