### ISSUE TITLE
Unable to install nightly releases

### ISSUE THREAD

**Issue by 0xJem** [foundry-rs/foundry-toolchain#45]
Config:
```
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # 2024-02-11
          version: nightly-93f094bfa54111f5689c346206d70ef45b4dd680
```
         
Job run output:
```
Run foundry-rs/foundry-toolchain@v1
  with:
    version: nightly-93f094bfa54111f5689c346[2](https://github.com/Axis-Fi/moonraker/actions/runs/7868299448/job/21518458614?pr=43#step:8:2)06d70ef45b4dd680
    cache: true
  env:
    FOUNDRY_PROFILE: ci
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
Downloading Foundry 'nightly-93f094bfa54111f5689c346206d70ef45b4dd680' from: https://github.com/foundry-rs/foundry/releases/download/nightly-93f094bfa54111f5689c346206d70ef45b4dd680/foundry_nightly_linux_amd64.tar.gz
Error: Error: Unexpected HTTP response: 404
```

This only started happening a few days ago. I updated to the latest nightlies (in case they were deleted), and it still happened. It seems like the URL format is different.
