### ISSUE TITLE
404 error when trying to download nightly

### ISSUE THREAD

**Issue by samlaf** [foundry-rs/foundry-toolchain#53]
All of my pipelines are currently broken by
<img width="632" alt="image" src="https://github.com/foundry-rs/foundry-toolchain/assets/9342524/00159d39-b7a3-4cb4-bc6f-4557b7834c42">

I checked and the url https://github.com/foundry-rs/foundry/releases/download/nightly/foundry_nightly_linux_amd64.tar.gz indeed isn't working (is this a github issue??)

The release url with commit hash https://github.com/foundry-rs/foundry/releases/download/nightly-88011569efcebc9152267be217c8cfbedc32c07c/foundry_nightly_linux_amd64.tar.gz is working however.

But it seems like even if I update my input to
```
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-88011569efcebc9152267be217c8cfbedc32c07c
```
the action [removes the commit hash](https://github.com/foundry-rs/foundry-toolchain/blob/8f1998e9878d786675189ef566a2e4bf24869773/src/utils.js#L4C18-L4C62)? Why is that?
