### ISSUE TITLE
Something in the latest versions of foundry is causing my github pipeline to fail (it was working before)

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry-toolchain#9]
![image](https://user-images.githubusercontent.com/6032276/177110328-6d5e2983-76ea-493e-b4aa-25771330a245.png)

Rerunning old tests also breaks on tests that used to pass, so potentially something new in the latest foundry is causing an issue.

It would be super nice to be able to specify a fixed version of foundry rather than nightly to prevent these kinds of issues in the future.

Here is my pipeline:
```yaml
name: Run Contract FORGE Tests

on:
  pull_request:
    paths:
      - "contracts/**/*.sol"
      - "contracts/test/**"

env:
  FOUNDRY_PROFILE: ci # This foundry profile is set to test the contracts slighly more vigorously.

defaults:
  run:
    working-directory: ./contracts

jobs:
  run-forge-contract-tests:
    name: Run contract FORGE tests
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache contract node_modules
        id: cache_contracts_node_modules
        uses: actions/cache@v2
        with:
          path: ~/work/monorepo/monorepo/contracts/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('~/work/monorepo/monorepo/contracts/yarn.lock') }}

      - name: install node packages
        if: steps.cache_contracts_node_modules.outputs.cache-hit != 'true'
        id: install_node_packages_contracts
        run: |
          yarn

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly # Note be careful, this might break at some point! We should fix a version rather - wasn't clear what the version was though from docs at time

      - name: Cache the foundry/forge cache
        id: cache_foundry_compile
        uses: actions/cache@v2
        with:
          path: |
            ~/work/monorepo/monorepo/contracts/cache
            ~/work/monorepo/monorepo/contracts/out
          key: ${{ runner.os }}-foundry-cache-v0.8.15-${{ hashFiles('~/work/monorepo/monorepo/contracts/contracts/**') }}
          restore-keys: |
            ${{ runner.os }}-foundry-cache-v0.8.15

      - name: Install forge dependencies
        id: run_install_dependencies
        run: |
          forge install

      - name: Pre-build contracts for following steps
        id: build_contracts
        run: |
          forge build #--extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers

      - name: Run forge tests
        id: run_forge_tests
        run: |
          forge snapshot --check # -vvvv means that all stack and setup traces are displayed

      ## No benefit to running slither in the pipeline currently... 😢
      # - name: Run Slither
      #   id: slither
      #   uses: crytic/slither-action@v0.1.0
      #   continue-on-error: true
      #   with:
      #     ignore-compile: true
      #     node-version: 16
      #     sarif: results.sarif

      # # TODO:  re-add this once github has enabled this feature for our account.
      # - name: Upload SARIF file
      #   id: upload-sarif-file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}
```

I'm unable to replicate this failure locally, and multiple people from my team also don't have the issue locally, so it seems like it is something about how the pipeline takes the output from build.
